// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOza4B3ctouUuHO8Efe59Uns_DNHS-iY',
    appId: '1:906586973190:web:0ae6541b7f252e75fecf87',
    messagingSenderId: '906586973190',
    projectId: 'psmn2025-jose',
    authDomain: 'psmn2025-jose.firebaseapp.com',
    storageBucket: 'psmn2025-jose.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6MSWXZzBXOU4xxRpqUgTtRag4F8HolrI',
    appId: '1:906586973190:android:21ad8ce473cb090ffecf87',
    messagingSenderId: '906586973190',
    projectId: 'psmn2025-jose',
    storageBucket: 'psmn2025-jose.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMOtZETAF-DtlFoYSNYnLxhVzaqwRLgQ',
    appId: '1:906586973190:ios:f61a2150ff048d2bfecf87',
    messagingSenderId: '906586973190',
    projectId: 'psmn2025-jose',
    storageBucket: 'psmn2025-jose.firebasestorage.app',
    androidClientId: '906586973190-namb4g335cf8cs6dgfua6ipk76a4ce6o.apps.googleusercontent.com',
    iosClientId: '906586973190-72p8dh8ep137mkcj6gse2seaqvb3qpop.apps.googleusercontent.com',
    iosBundleId: 'com.example.miEstudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwMOtZETAF-DtlFoYSNYnLxhVzaqwRLgQ',
    appId: '1:906586973190:ios:f61a2150ff048d2bfecf87',
    messagingSenderId: '906586973190',
    projectId: 'psmn2025-jose',
    storageBucket: 'psmn2025-jose.firebasestorage.app',
    androidClientId: '906586973190-namb4g335cf8cs6dgfua6ipk76a4ce6o.apps.googleusercontent.com',
    iosClientId: '906586973190-72p8dh8ep137mkcj6gse2seaqvb3qpop.apps.googleusercontent.com',
    iosBundleId: 'com.example.miEstudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlOza4B3ctouUuHO8Efe59Uns_DNHS-iY',
    appId: '1:906586973190:web:976b84687b3a57befecf87',
    messagingSenderId: '906586973190',
    projectId: 'psmn2025-jose',
    authDomain: 'psmn2025-jose.firebaseapp.com',
    storageBucket: 'psmn2025-jose.firebasestorage.app',
  );

}